#ifndef __BOARD_CONF_H__
#define __BOARD_CONF_H__

#define CONFIG_SYSCLK_FREQ     8000000
// #define CONFIG_SYSCLK_FREQ     64000000

#define CONFIG_REDIRECT_PRINTF 1
#define CONFIG_REDIRECT_CWUART CW_UART1

#endif
